# Generated by Django 5.2.5 on 2025-09-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
