# Generated by Django 5.2.6 on 2025-09-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
    ]
