# Generated by Django 5.2.5 on 2025-08-22 15:00

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='resource',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete= models.deletion.CASCADE,
                to='consulting.Resource'
            ),
        ),
    ]
