# Generated by Django 5.2.5 on 2025-08-22 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20250822_1800'),
    ]

    operations = [
    ]
