# Generated by Django 5.2.6 on 2025-09-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_waitingquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitingquestion',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
