# Generated by Django 5.2.6 on 2025-09-06 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_waitingquestion_answered'),
    ]

    operations = [
    ]
