# Generated by Django 5.2.4 on 2025-08-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('consultant', 'Consultant'), ('admin', 'Admin')], max_length=10),
        ),
    ]
