# Generated by Django 5.2.6 on 2025-09-06 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
