# Generated by Django 5.2.4 on 2025-08-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdomain',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
