# Generated by Django 5.2.4 on 2025-08-03 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerationrequests',
            name='consultant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_relations', to='consulting.consultant'),
        ),
    ]
