# Generated by Django 5.2.4 on 2025-08-18 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0003_alter_subdomain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultant',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_consultants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultant',
            name='years_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsultantApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.IntegerField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('languages', models.CharField(blank=True, max_length=255, null=True)),
                ('documentation', models.FileField(upload_to='consultant_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_applications', to='consulting.domain')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
                ('sub_domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_applications', to='consulting.subdomain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RegisterationRequests',
        ),
    ]
