# Generated by Django 5.2.4 on 2025-08-03 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_alter_registerationrequests_consultant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='question',
        ),
        migrations.AddField(
            model_name='consultation',
            name='sub_domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subdomain', to='consulting.subdomain'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='domain', to='consulting.domain'),
        ),
    ]
