# Generated by Django 5.2.4 on 2025-08-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0004_consultant_cost_consultant_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultantapplication',
            name='documentation',
        ),
        migrations.RemoveField(
            model_name='consultantapplication',
            name='education',
        ),
        migrations.RemoveField(
            model_name='consultantapplication',
            name='title',
        ),
        migrations.AlterField(
            model_name='consultantapplication',
            name='cost',
            field=models.IntegerField(default=0),
        ),
    ]
