# Generated by Django 5.2.4 on 2025-08-20 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0005_remove_consultantapplication_documentation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='text',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='consultant',
            name='review_count',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='number_of_used',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='sub_domain',
        ),
        migrations.AddField(
            model_name='consultation',
            name='answer_end',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='answer_start',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='confidence_answer',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='confidence_question',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='question',
            field=models.TextField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='question_end',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='question_start',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='resource',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consulting.resource'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consulting.consultant'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='consulting.consultant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'consultant')},
            },
        ),
    ]
