# Generated by Django 5.2.4 on 2025-08-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0005_remove_consultation_question_consultation_sub_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
