# Generated by Django 5.2.4 on 2025-08-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0006_rename_text_consultation_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='consultant',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
