# Generated by Django 5.2.4 on 2025-08-21 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0007_consultant_rating_consultant_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultants', to='consulting.resource'),
        ),
        migrations.AddField(
            model_name='consultantapplication',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultant_applications_photo', to='consulting.resource'),
        ),
    ]
