# Generated by Django 5.2.4 on 2025-09-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0009_alter_resource_relation_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='answer_end',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='question_start',
        ),
    ]
