# Generated by Django 5.2.5 on 2025-09-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0010_remove_consultation_answer_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='subdomain',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ResourceQualityCheck',
        ),
    ]
