# Generated by Django 5.2.6 on 2025-09-04 09:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0011_domain_status_subdomain_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='answer_start',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='question_end',
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_type',
            field=models.CharField(blank=True, choices=[('audio', 'Audio'), ('video', 'Video'), ('text', 'Text')], null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='end_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='start_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='confidence_answer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='confidence_question',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='consulting.resource'),
        ),
        migrations.CreateModel(
            name='ResourceQualityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('quality_report', models.JSONField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_check', to='consulting.resource')),
            ],
        ),
    ]
