# Generated by Django 5.2.6 on 2025-09-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulting', '0012_remove_consultation_answer_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='start_time',
        ),
    ]
